# Setup
title:        Monkey Blog
tagline:      I hear and I forget, I see and I remember, I do and I understand
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       cs.yi
  url:        https://monkey-knight.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-cayman
mathjax: true